### PR TITLE
[WIP] Generate iCal files for the deadlines

### PR DESCRIPTION
**Pull request by f0rki**
I whipped up quick ical generation template. I have only tested with my evolution calendar app so far, but it seems to work. I think it is quite nice to also put the deadlines into my calendar.

What do you think about this feature?

### CODE REVIEW

**Comment by clementfung** [comment]
Looks good to me, I don't use iCal much myself but I just tested an import with my google calendar and it works.
Btw, the "parent" page for this site, [aideadlin.es](aideadlin.es), also has an ical feature, for reference.

**Comment by clementfung** [comment]
@f0rki Is this PR still WIP? Or are you happy to have it merged? :smile:

**Comment by f0rki** [comment]
@clementfung let me have another look; rebase; do some testing. I'll ping you when I think it is ready to merge :)

**Comment by f0rki** [comment]
@clementfung oh sorry for the delay. I think this can be merged. I looked at a couple of calendar entries in my calendar and everything seems fine.

**Comment by clementfung** [comment]
Sounds good, thank you again for all your help!

**Pull request merged**
