### PR TITLE
Update conferences.yml

### PR DESCRIPTION
**Pull request by alireza12t**
Add FPS 2022 dates

### CODE REVIEW

**Comment by alireza12t** [comment]
@txin @romen @f0rki Can someone check this pull request?

**Comment by clementfung** [comment]
Thanks for the reminder, I cleaned up the formatting a little bit, otherwise looks good!

**Comment by alireza12t** [comment]
@clementfung  Thanks, May I ask why you delete other deadlines? there are two deadlines for the papers 
Screen Shot 2022-09-21 at 10 48 21 AM

**Comment by clementfung** [comment]
To avoid confusion, we only show full paper submission deadlines (no abstracts, conference registration, etc). 
Other conferences have multiple deadlines but these are rotating deadlines where each deadline is a paper submission deadline.

**Pull request merged**
