### PR TITLE
Add SciSec 2024

### PR DESCRIPTION
**Pull request by MarazMia**

### CODE REVIEW

**Comment by clementfung** [comment]
Why are you modifying the example in the README?

**Comment by MarazMia** [comment]
There was a misunderstanding. Instead of editing the yml file, I edited the README file. I really seek apology for that. I created a new pull request and this time I added a conference into the yml file.

**Comment by MarazMia** [comment]
Hi,

There was a bit of misunderstanding. My supervisor Dr. Pritom asked me to
add the SciSec <https://scisec.org/> conference record within your list of
security conference deadlines as he is serving as the publicity chair of
the SciSec 2024 conference. However, I have mistakenly updated the README
file instead of adding it to the instructed _data/conferences.yml file. I
updated the branch and this time I put the conference details on the
instructed .yml file. Please merge the edit and sorry again for the
confusion. Thanks.

**Comment by clementfung** [comment]
No problem! I fixed some minor formatting and have merged it. Thanks!

**Pull request merged**
