### PR TITLE
OSCo added

### PR DESCRIPTION
**Pull request by bilkobe**
New conference is added

### CODE REVIEW

**Comment by clementfung** [comment]
Are there any talks or papers presented as a part of this conference? 
I couldn't see what the Aug 31 deadline actually refers to.

**Comment by bilkobe** [comment]
> Are there any talks or papers presented as a part of this conference? I couldn't see what the Aug 31 deadline actually refers to.

Since this is an [open-space format ](https://opensecurityconference.org/open-space/) conference, there are no specific CFP and deadline. I added it since the parameter is required just in case.

**Comment by bilkobe** [comment]
General Schedule Plan is in place on https://opensecurityconference.org/conference/schedule

**Comment by clementfung** [comment]
Sorry, this page is meant for academic conferences with paper submissions and their corresponding deadlines.
I do not think that OSCo fits this description and will close this PR.

**Pull request closed without merging**
